### ISSUE TITLE
SQLite database

### ISSUE THREAD

**Issue by nikita-moor** [emanuelboboiu/Latin-Romanian-Dictionary-Android#1]
Dear Emanuel Boboiu,

You removed the actual SQLite database from the repository. 

1. What is its legal status?
1. Can I download it somewhere?

It seems you are related to <https://www.limbalatina.ro/dictionar.php>, so I would like to ask your permission on redistribution of this dictionary. I'm the main developer of  [latin-dict.github.io](https://latin-dict.github.io/) and would like to have this Latin-Romanian dictionary in our collection.

Answer here, please, or contact me by [email](https://latin-dict.github.io/about.html) if you wish to discuss our collaboration.

**Comment by emanuelboboiu** [comment]
Hi there,

Sorry for my delay in response.
My database is created manually, each word was inserted one by one by
us, two collaborators.
That's why I didn't want to be public.
I could give you the SQLLite DB.
My question is> can I have a latin - English DB in return? It would be
useful for my App, I could develope more options and other ideas.

Thanks,
    Emanuel Boboiu


On 6/24/23, Nikita Moor ***@***.***> wrote:
> You removed the actual SQLite database from the repository.
>
> 1. What is its legal status?
> 1. Can I download it somewhere?
>
> It seems you are related to <https://www.limbalatina.ro/dictionar.php>, so I
> would like to ask your permission on redistribution of this dictionary. I'm
> the main developer of  [latin-dict.github.io](https://latin-dict.github.io/)
> and would like to have this Latin-Romanian dictionary in our collection.
>
> Contact me [email](https://latin-dict.github.io/about.html), please, if you
> wish to discuss our collaboration.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/emanuelboboiu/Latin-Romanian-Dictionary-Android/issues/1
> You are receiving this because you are subscribed to this thread.
>
> Message ID:
> ***@***.***>


-- 
Emanuel Boboiu (MANU)
www.limbalatina.ro

**Comment by nikita-moor** [comment]
> can I have a latin - English DB?

There are several Lat-Eng dictionaries in my collection, you can use them legally free:

**Lewis, 1890**: [An Elementary Latin Dictionary](https://latin-dict.github.io/dictionaries/Lewis1890.html)
Source (TEI format): https://github.com/PerseusDL/lexica/tree/master/CTS_XML_TEI/perseus/pdllex/lat/ls
License: CC BY-SA 4.0 + statement

**Lewis & Short, 1879**: [A Latin Dictionary](https://latin-dict.github.io/dictionaries/LewisShort1879.html)
Source (TEI format): https://github.com/PerseusDL/lexica/tree/master/CTS_XML_TEI/perseus/pdllex/lat/ls
License: CC BY-SA 4.0 + statement

**Simpson, 1959**: [Cassell’s Latin Dictionary](https://latin-dict.github.io/dictionaries/Simpson1959.html)
Source (custom XML): https://www.codeproject.com/Articles/72737/Latin-Textbook-and-Look-up-Table-in-C
License: CPOL (allows commercial and derivative works)

From other collections:

**Marchant & Charles, 1904**: [Cassell's Latin dictionary](https://archive.org/details/cassellslatindic00marc)
Source (plain text): https://github.com/TrentonJ/Cassell-s-Latin-Dictionary
License: Public Domain

**FreeDict, 2017**: [Latin-English FreeDict Dictionary](http://dict.org/bin/Dict?Form=Dict3&Database=fd-lat-eng) (2305 words)
Source (TEI): https://github.com/freedict/fd-dictionaries/tree/master/lat-eng
LIcense: GNU GPL 2.0

> That's why I didn't want to be public.

I respect your decision and will not disturb you in the future. If you decide to make your dictionary public, feel free to contact me. Anyway, I wish your project success, your work is very important and valuable.

**Comment by emanuelboboiu** [comment]
Hi again,

I didn't understand, what you exactly want.
Do you need the database or...

I use my database in two places>

An application for Android, published in Play Store:
https://play.google.com/store/apps/details?id=ro.limbalatina.dictionarlatinroman

A web interface at:
https://www.limbalatina.ro/dictionar.php

Both are public.

     Thank you
P.S.: I didn't read about your project, maybe that's why I don't
understand what you want with my Latin - Romanian Dictionary.
I would be happy to collaborate.

   Emanuel Boboiu


On 8/4/23, Nikita Moor ***@***.***> wrote:
> Closed #1 as completed.
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/emanuelboboiu/Latin-Romanian-Dictionary-Android/issues/1#event-10009328769
> You are receiving this because you commented.
>
> Message ID:
> ***@***.***>


-- 
Emanuel Boboiu (MANU)
www.limbalatina.ro
